#!/bin/bash
#
# creates 1kolokvij.html

HEADER=`cat ../../templates/head`

#tmpFileKolokvij='1kolokvij.temp'
tmpFileKolokvij=`mktemp`
echo "$HEADER" > "$tmpFileKolokvij"
cat 1kolokvij.txt | sed 's/^-$//' | \
sed -r 's/(^[IV]+\. [ A-Ž–]+$)/## \1/' | \
sed -r 's/(^[0-9]+\. [ A-Ž,:?–]+$)/### \1/' | \
sed -r 's/(^[ A-Ž0-9\-]{3,}:*)/#### \1\n/' >> "$tmpFileKolokvij"
markdown "$tmpFileKolokvij" > 1kolokvij.html
