#!/bin/bash
#
# Usage: questioneer <text> <list-of-questions>
# Asks the question, waits for the input, then prits the answer

# QUESTION:
question=`cat "$1" | grep '^[0-9]\. [A-Z]' | tr -d ':' | sort -R | head -1`
echo "$question"
read
# ANSWER:
nextQuestion=`grep "$question" -A1 "$2" | tail -n+2`
sed -n "/$question/,/$nextQuestion/p" "$1" | head -n-1

