#!/bin/bash
#
# Usage: reset-page 
# Creates html page from text files using markdown command. 

HEADER=`cat ../scripts/header`

# create 1kolokvij.html
#tmpFileKolokvij='1kolokvij.temp'
tmpFileKolokvij=`mktemp`
echo "$HEADER" > "$tmpFileKolokvij"
cat 1kolokvij.txt | sed 's/^-$//' | \
sed -r 's/(^[IV]+\. [ A-Ž–]+$)/## \1/' | \
sed -r 's/(^[0-9]+\. [ A-Ž,:?–]+$)/### \1/' | \
sed -r 's/(^[ A-Ž0-9\-]{3,}:*)/#### \1\n/' >> "$tmpFileKolokvij"
markdown "$tmpFileKolokvij" > 1kolokvij.html
 
# create 3kolokvijERP.html
#tmpFileKolokvij='1kolokvij.temp'
tmpFileKolokvij2=`mktemp`
echo "$HEADER" > "$tmpFileKolokvij2"
cat 3kolokvijERP.txt >> "$tmpFileKolokvij2"
markdown "$tmpFileKolokvij2" > 3kolokvijERP.html

# create text.html
../scripts/create-text-html
