#!/bin/bash
#
# Usage: create-index-html 
# Creates index.html in projects root.

cat ../templates/head > ../index.html
cat ../templates/index >> ../index.html
echo "<blockquote>" >> ../index.html

# adds list of links to the individual courses:
pages=$(find ../site -maxdepth 1 -mindepth 1 -type d)
while read -r line; do
	acronim=`basename "$line"`
	acronimCap=`echo "$acronim" | tr [a-z] [A-Z]`
	longName=`cat ../site/$acronim/text.html | \
				grep '<h1>' | \
				sed 's/<[/]*h1>//g'`
	echo "<a href=site/$acronim/text.html>$acronimCap - $longName</a><br>" \
			>> ../index.html
done <<< "$pages"

echo "</blockquote>" >> ../index.html
