#!/bin/bash
#
# Usage: create-text-html <dir> <html-head-path>
# Creates text.html page from text.md file using markdown command. 

course=`basename "$1"`
tmpFileText=`mktemp`
# add head section
cat "$2" > "$tmpFileText"
# add link to text file on github
echo "<a href=\"../../index.html\">Domov</a>" >> "$tmpFileText"

echo "<a href=\"https://github.com/gto76/fri/blob/gh-pages/site/$course/text.md\">Uredi</a>" >> "$tmpFileText"

# skip first divider
head -n7 "$1"text.md >> "$tmpFileText"
scripts/parse-timetables "$1"text.md  | tail -n+9  >> "$tmpFileText"

# parse
markdown "$tmpFileText" > "$1"text.html

