#!/bin/bash
#
# Usage: display-page
# Makes the page and opens it with chrome.
# Needs to be called from the course's dir.

courseDir=`basename $PWD`
(cd ../..
make "$courseDir")
google-chrome text.html &> /dev/null &
